
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vtvtfodicyslqmaunxop.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0dnRmb2RpY3lzbHFtYXVueG9wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MjUzODMsImV4cCI6MjA2NDUwMTM4M30.8oD1APHSMqm0xubN9DWn8Dwv74Sl3TMiezWxCvzQp6w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
